### ISSUE TITLE
release checklist

### ISSUE THREAD

**Issue by lysevi** [lysevi/dariadb#109]
- [ ] - update git submodules.
- [ ] - Code test coverage must be 90-100%.
- [ ] - SANITIZERs dont find errors.
- [ ] - Update readme benchmarks.
- [ ] - Update changelog file from closed issues.
- [ ] - Project version in CMakeLists.txt.
- [ ] - Update [examples](https://github.com/lysevi/dariadb-example/blob/master/main.cpp).
- [ ] - Indentation.
